// Add missing resource types from Winuser.h
// https://learn.microsoft.com/en-us/windows/win32/menurc/resource-types

#define RT_MANIFEST 24

// IDs for resource items

// IME DLL
#define IDM_MANIFEST                    1
#define IDS_TEXT_SERVICE_DISPLAY_NAME   101
#define IDI_MAINICON                    102
#define IDI_MODE_ALPHA                  103
#define IDI_MODE_ALPHA_W                104
#define IDI_MODE_CONTINUOUS             105
#define IDI_MODE_CONTINUOUS_W           106
#define IDI_MODE_PRO                    107
#define IDI_MODE_PRO_W                  108
#define IDI_MODE_BASIC                  109
#define IDI_MODE_BASIC_W                110
#define IDI_SETTINGS                    111
#define IDI_SETTINGS_W                  112
#define IDR_POPUP_MENU                  113
#define IDS_CONTINUOUS_MODE             1000
#define IDS_BASIC_MODE                  1001
#define IDS_MANUAL_MODE                 1002
#define IDS_DIRECT_MODE                 1003
#define IDS_OPEN_SETTINGS               1004

// Settings EXE
#define ID_SETTINGS_MANIFEST            2
#define IDD_ABOUTTAB                    2000
#define IDS_LIGHT_THEME                 2001
#define IDS_DARK_THEME                  2002
#define IDS_DISPLAY_LANGUAGE_EN         2003
#define IDS_DISPLAY_LANGUAGE_HANLO      2004
#define IDS_DISPLAY_LANGUAGE_LO         2005
#define IDS_WINDOW_CAPTION              2006
#define IDD_APPEARANCETAB               2007
#define IDL_COLOR                       2008
#define IDC_COMBOBOX_THEME_COLOR        2009
#define IDL_CANDIDATE_SIZE              2010
#define IDC_CANDIDATE_SIZE              2011
#define IDL_CANDIDATE_SIZE_S            2012
#define IDL_CANDIDATE_SIZE_L            2013
#define IDC_EDIT_TRY                    2014
#define IDL_EDIT_TRY                    2015
#define IDC_DISPLAY_LANGUAGE            2016
#define IDL_DISPLAY_LANGUAGE            2017
#define IDD_INPUTTAB                    2018
#define IDL_INPUTMODE                   2019
#define IDC_INPUTMODE_CONTINUOUS        2020
#define IDC_INPUTMODE_BASIC             2021
#define IDC_INPUTMODE_PRO               2022
#define IDL_INPUTMODE_HOTKEY            2023
#define IDC_INPUTMODE_KEY_COMBO         2024
#define IDS_INPUTMODE_KEY_CTRL_PERIOD   2025
#define IDS_INPUTMODE_KEY_CTRL_BACKTICK 2026
#define IDL_ON_OFF_HOTKEY               2027
#define IDC_ON_OFF_HOTKEY_COMBO         2028
#define IDS_ON_OFF_HOTKEY_SHIFT         2029
#define IDS_ON_OFF_HOTKEY_ALTBACKTICK   2030
#define IDL_DEFAULT_PUNCTUATION         2031
#define IDC_PUNCTUATION_COMBO           2032
#define IDS_PUNCT_FULL_WIDTH            2033
#define IDS_PUNCT_HALF_WIDTH            2034
#define IDL_TONE_KEYS                   2035
#define IDC_TONE_KEYS_COMBO             2036
#define IDS_TONE_KEYS_NUMERIC           2037
#define IDS_TONE_KEYS_TELEX             2038
#define IDL_DOTTED_O_KEY                2039
#define IDC_DOTTED_O_KEY_COMBO          2040
#define IDS_DOTTED_O_OU                 2041
#define IDS_DOTTED_O_OO                 2042
#define IDS_DOTTED_O_Y                  2043
#define IDL_NASAL_KEY                   2044
#define IDC_NASAL_KEY_COMBO             2045
#define IDS_NASAL_NN                    2046
#define IDS_NASAL_V                     2047
#define IDC_OPTION_DOTTED_KHIN          2048
#define IDC_OPTION_AUTOKHIN             2049
#define IDC_OPTION_EASY_CH              2050
#define IDC_OPTION_UPPERCASE_NASAL      2051
#define IDL_HYPHEN_KEY                  2052
#define IDC_HYPHEN_KEY_COMBO            2053
#define IDS_HYPHEN_KEY_HYPHEN           2054
#define IDS_HYPHEN_KEY_V                2055
#define IDD_DICTIONARYTAB               2056
#define IDL_RESET_USERDATA              2057
#define IDC_RESET_USERDATA_BTN          2058
#define IDL_RESET_USERDATA_BTN_DONE     2059
#define IDL_EDIT_USERDICT               2060
#define IDC_EDIT_USEDICT_BTN            2061

#define IDC_STATIC                        -1
