name: Khiin
options:
  bundleIdPrefix: app.khiin
packages:
  KhiinBridge:
    path: ../KhiinBridge
  KhiinSwift:
    path: ../shared
  SwiftProtobuf:
    url: https://github.com/apple/swift-protobuf
    from: 1.21.0
  SwiftyBeaver:
    github: SwiftyBeaver/SwiftyBeaver
    from: 2.0.0
targets:
  Khiin:
    type: application
    platform: iOS
    deploymentTarget: 15.0
    sources: [Khiin]
    dependencies:
      - target: Keyboard
    settings:
      base:
        INFOPLIST_FILE: Khiin/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: app.khiin.khiin
  Keyboard:
    platform: iOS
    deploymentTarget: 15.0
    type: app-extension
    sources: [Keyboard, ../../resources/khiin.db]
    dependencies:
      - package: KhiinBridge
      - package: KhiinSwift
      - package: SwiftProtobuf
    settings:
      base:
        INFOPLIST_FILE: Keyboard/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: app.khiin.khiin.keyboard
