[workspace]
members = [
    "app/client",
    "app/src-tauri",
    "app/settings",
    "android/rust",
    "cli",
    "khiin",
    "protos",
    "swift/bridge",
    "windows/ime",
    "windows/settings"
]
