[target.aarch64-apple-ios]
rustflags = [
    "-C", "link-arg=-syslibroot",
    "-C", "link-arg=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk"
]

[target.x86_64-apple-ios]
rustflags = [
    "-C", "link-arg=-syslibroot",
    "-C", "link-arg=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk"
]

[target.aarch64-apple-ios-sim]
rustflags = [
    "-C", "link-arg=-syslibroot",
    "-C", "link-arg=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk"
]

