[package]
name = "khiin_swift"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
khiin = { path = "../../khiin" }
khiin_protos = { path = "../../protos" }
swift-bridge = { path = "../../../swift-bridge" }

[build-dependencies]
swift-bridge-build = { path = "../../../swift-bridge/crates/swift-bridge-build" }
