[package]
name = "khiin"
version = "0.1.0"
edition = "2021"
authors = ["Ko An Iong <aiongtaigi@gmail.com"]
publish = false

[lib]
crate-type = ["lib"]

[dependencies]
anyhow = "1.0.70"
khiin_protos = { path = "../protos" }
lazy-regex = "2.5.0"
once_cell = "1.17.1"
protobuf = "3.2.0"
regex = "1.7.3"
unicode-normalization = "0.1.22"
