#ifndef khiin_ios_bindings_h
#define khiin_ios_bindings_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>


char *rust_bytes_to_string(const uint8_t *data, size_t len);

void rust_string_free(char *s);

#endif /* khiin_ios_bindings_h */
